// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: registry/v1/person.proto

package registryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Person struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=first_name,proto3" json:"first_name,omitempty"`
	// Types that are assignable to Type:
	//
	//	*Person_Admin_
	//	*Person_Manager_
	//	*Person_Client_
	Type isPerson_Type `protobuf_oneof:"type"`
}

func (x *Person) Reset() {
	*x = Person{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registry_v1_person_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person) ProtoMessage() {}

func (x *Person) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_person_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person.ProtoReflect.Descriptor instead.
func (*Person) Descriptor() ([]byte, []int) {
	return file_registry_v1_person_proto_rawDescGZIP(), []int{0}
}

func (x *Person) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (m *Person) GetType() isPerson_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Person) GetAdmin() *Person_Admin {
	if x, ok := x.GetType().(*Person_Admin_); ok {
		return x.Admin
	}
	return nil
}

func (x *Person) GetManager() *Person_Manager {
	if x, ok := x.GetType().(*Person_Manager_); ok {
		return x.Manager
	}
	return nil
}

func (x *Person) GetClient() *Person_Client {
	if x, ok := x.GetType().(*Person_Client_); ok {
		return x.Client
	}
	return nil
}

type isPerson_Type interface {
	isPerson_Type()
}

type Person_Admin_ struct {
	Admin *Person_Admin `protobuf:"bytes,2,opt,name=admin,proto3,oneof"`
}

type Person_Manager_ struct {
	Manager *Person_Manager `protobuf:"bytes,3,opt,name=manager,proto3,oneof"`
}

type Person_Client_ struct {
	Client *Person_Client `protobuf:"bytes,4,opt,name=client,proto3,oneof"`
}

func (*Person_Admin_) isPerson_Type() {}

func (*Person_Manager_) isPerson_Type() {}

func (*Person_Client_) isPerson_Type() {}

type Person_Admin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YearsInCharge int64 `protobuf:"varint,1,opt,name=years_in_charge,json=yearsInCharge,proto3" json:"years_in_charge,omitempty"`
	HasHolidays   bool  `protobuf:"varint,2,opt,name=has_holidays,json=hasHolidays,proto3" json:"has_holidays,omitempty"`
}

func (x *Person_Admin) Reset() {
	*x = Person_Admin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registry_v1_person_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Admin) ProtoMessage() {}

func (x *Person_Admin) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_person_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Admin.ProtoReflect.Descriptor instead.
func (*Person_Admin) Descriptor() ([]byte, []int) {
	return file_registry_v1_person_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Person_Admin) GetYearsInCharge() int64 {
	if x != nil {
		return x.YearsInCharge
	}
	return 0
}

func (x *Person_Admin) GetHasHolidays() bool {
	if x != nil {
		return x.HasHolidays
	}
	return false
}

type Person_Manager struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManagesClients bool `protobuf:"varint,1,opt,name=manages_clients,json=managesClients,proto3" json:"manages_clients,omitempty"`
}

func (x *Person_Manager) Reset() {
	*x = Person_Manager{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registry_v1_person_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Manager) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Manager) ProtoMessage() {}

func (x *Person_Manager) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_person_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Manager.ProtoReflect.Descriptor instead.
func (*Person_Manager) Descriptor() ([]byte, []int) {
	return file_registry_v1_person_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Person_Manager) GetManagesClients() bool {
	if x != nil {
		return x.ManagesClients
	}
	return false
}

type Person_Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subscription string `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
}

func (x *Person_Client) Reset() {
	*x = Person_Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registry_v1_person_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Person_Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Person_Client) ProtoMessage() {}

func (x *Person_Client) ProtoReflect() protoreflect.Message {
	mi := &file_registry_v1_person_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Person_Client.ProtoReflect.Descriptor instead.
func (*Person_Client) Descriptor() ([]byte, []int) {
	return file_registry_v1_person_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Person_Client) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

var File_registry_v1_person_proto protoreflect.FileDescriptor

var file_registry_v1_person_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x82, 0x03, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x05,
	0x61, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x48, 0x00, 0x52, 0x05, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x12,
	0x37, 0x0a, 0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x52,
	0x0a, 0x05, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x0f, 0x79, 0x65, 0x61, 0x72, 0x73,
	0x5f, 0x69, 0x6e, 0x5f, 0x63, 0x68, 0x61, 0x72, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x79, 0x65, 0x61, 0x72, 0x73, 0x49, 0x6e, 0x43, 0x68, 0x61, 0x72, 0x67, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x68, 0x61, 0x73, 0x5f, 0x68, 0x6f, 0x6c, 0x69, 0x64, 0x61, 0x79, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x48, 0x6f, 0x6c, 0x69, 0x64, 0x61,
	0x79, 0x73, 0x1a, 0x32, 0x0a, 0x07, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x27, 0x0a,
	0x0f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x73, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x73, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x2c, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x42, 0x06, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x42, 0xa8, 0x01, 0x0a,
	0x0f, 0x63, 0x6f, 0x6d, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x76, 0x31,
	0x42, 0x0b, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61, 0x75,
	0x72, 0x79, 0x39, 0x35, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x69, 0x66, 0x79, 0x2f, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2f, 0x76,
	0x31, 0x3b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x52,
	0x58, 0x58, 0xaa, 0x02, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x2e, 0x56, 0x31,
	0xca, 0x02, 0x0b, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42,
	0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x79, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_registry_v1_person_proto_rawDescOnce sync.Once
	file_registry_v1_person_proto_rawDescData = file_registry_v1_person_proto_rawDesc
)

func file_registry_v1_person_proto_rawDescGZIP() []byte {
	file_registry_v1_person_proto_rawDescOnce.Do(func() {
		file_registry_v1_person_proto_rawDescData = protoimpl.X.CompressGZIP(file_registry_v1_person_proto_rawDescData)
	})
	return file_registry_v1_person_proto_rawDescData
}

var file_registry_v1_person_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_registry_v1_person_proto_goTypes = []interface{}{
	(*Person)(nil),         // 0: registry.v1.Person
	(*Person_Admin)(nil),   // 1: registry.v1.Person.Admin
	(*Person_Manager)(nil), // 2: registry.v1.Person.Manager
	(*Person_Client)(nil),  // 3: registry.v1.Person.Client
}
var file_registry_v1_person_proto_depIdxs = []int32{
	1, // 0: registry.v1.Person.admin:type_name -> registry.v1.Person.Admin
	2, // 1: registry.v1.Person.manager:type_name -> registry.v1.Person.Manager
	3, // 2: registry.v1.Person.client:type_name -> registry.v1.Person.Client
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_registry_v1_person_proto_init() }
func file_registry_v1_person_proto_init() {
	if File_registry_v1_person_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_registry_v1_person_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registry_v1_person_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Admin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registry_v1_person_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Manager); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_registry_v1_person_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Person_Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_registry_v1_person_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Person_Admin_)(nil),
		(*Person_Manager_)(nil),
		(*Person_Client_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_registry_v1_person_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registry_v1_person_proto_goTypes,
		DependencyIndexes: file_registry_v1_person_proto_depIdxs,
		MessageInfos:      file_registry_v1_person_proto_msgTypes,
	}.Build()
	File_registry_v1_person_proto = out.File
	file_registry_v1_person_proto_rawDesc = nil
	file_registry_v1_person_proto_goTypes = nil
	file_registry_v1_person_proto_depIdxs = nil
}

var OneofWrappers = []interface{}{
	(*Person_Admin_)(nil),
	(*Person_Manager_)(nil),
	(*Person_Client_)(nil),
}
